Document: gitcj
Title: Debian gitcj Manual
Author: <insert document author here>
Abstract: This manual describes what gitcj is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gitcj/gitcj.sgml.gz

Format: postscript
Files: /usr/share/doc/gitcj/gitcj.ps.gz

Format: text
Files: /usr/share/doc/gitcj/gitcj.text.gz

Format: HTML
Index: /usr/share/doc/gitcj/html/index.html
Files: /usr/share/doc/gitcj/html/*.html


